### ISSUE TITLE
Wrong path on `--conf-file` datalplane api example

### ISSUE THREAD

**Issue by bmiro** [haproxytech/haproxy-docker-debian#2]
In the haproxy.cfg there is a commented example to make the dataplaneapi work.

The specified `--config-file` is wrong and triggers the error:

```
<container-name>_1  | time="2021-02-24T17:27:16Z" level=fatal msg="The configuration file is not declared in the HAPROXY_CFGFILES environment variable, cannot start."
```

Is an strange error because both files are symlinked but the envvar `HAPROXY_CFGFILES` does not match the file of the example and the container dies.

Using the path `/usr/local/etc/haproxy/haproxy.cfg` that matches  `HAPROXY_CFGFILES` instead of the symlink works.

I've made a PR with the little documentation fix: #1 

I've only tested 2.2 lts but probably other versions should also be fixed.

**Comment by dkorunic** [comment]
Fixed with commit https://github.com/haproxytech/haproxy-docker-debian/commit/eb477a425472449846c7672018633ca6198d0df2. Thanks for reporting!
