### ISSUE TITLE
Use a non docker hub repository?

### ISSUE THREAD

**Issue by paul-civitas** [haproxytech/haproxy-docker-debian#9]
Currently haproxy images are published to dockerhub.

Five years ago this was fine. However recently dockerhub has a lot of issues. There is very strict rate limiting on it and due to it we're not allowed to pull images from dockerhub in our infrastructure.

Is there anyway you could publish images also to quay.io or google container registry or github's container registry or similar?

**Comment by dkorunic** [comment]
@paul-civitas In progress, I'll let you know when all our GHCRs have been enabled and images rebuilt and tagged. It will take at least a few days, given the huge amount of images in question.

**Comment by dkorunic** [comment]
GHCR builds are available for all of our HAProxy CE builds (Debian, Ubuntu, Alpine) w/ and w/o quictls.
